#!/bin/sh
#
# Usage:
#
#    sh install.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -B 0 -g
#
# To update it, re-run the above command.
#
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $LN -sf "$1" "$2"
}
handle_file_ln "/home/muqsit/.dotfiles/README.md" "/home/muqsit/.README.md"
handle_file_ln "/home/muqsit/.dotfiles/alacritty.yml" "/home/muqsit/.alacritty.yml"
handle_file_ln "/home/muqsit/.dotfiles/config/autostart/alt+f2.desktop" "/home/muqsit/.config/autostart/alt+f2.desktop"
handle_file_ln "/home/muqsit/.dotfiles/config/neofetch/config.conf" "/home/muqsit/.config/neofetch/config.conf"
handle_file_ln "/home/muqsit/.dotfiles/gitconfig" "/home/muqsit/.gitconfig"
handle_file_ln "/home/muqsit/.dotfiles/install.sh" "/home/muqsit/.install.sh"
handle_file_ln "/home/muqsit/.dotfiles/zshrc" "/home/muqsit/.zshrc"
